// Generated by scripts/merge_localizations.py. DO NOT EDIT DIRECTLY.
// Re-run `./scripts/merge_localizations.py` to regenerate after modifying .xcstrings files.

import Core
import Foundation

// MARK: - Root Translations Extension

public extension Translations {
    var home: HomeTranslations {
        HomeTranslations(manager: manager)
    }

    var scanner: ScannerTranslations {
        ScannerTranslations(manager: manager)
    }

    var settings: SettingsTranslations {
        SettingsTranslations(manager: manager)
    }

    var shell: ShellTranslations {
        ShellTranslations(manager: manager)
    }
}

// MARK: - Generated Feature & Component Translation Namespaces

@MainActor
public struct HomeTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var title: String {
        manager.translate("home.title", default: "Home")
    }
}

@MainActor
public struct ScannerTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var comingSoon: ScannerComingSoonTranslations {
        ScannerComingSoonTranslations(manager: manager)
    }

    public var title: String {
        manager.translate("scanner.title", default: "Scanner")
    }
}

@MainActor
public struct ScannerComingSoonTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var message: String {
        manager.translate(
            "scanner.comingSoon.message",
            default: "This tab is a stub in the template — wire a real scanner into ScannerFeature."
        )
    }

    public var title: String {
        manager.translate("scanner.comingSoon.title", default: "Scanner coming soon")
    }
}

@MainActor
public struct SettingsTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var account: SettingsAccountTranslations {
        SettingsAccountTranslations(manager: manager)
    }

    public var appInfo: SettingsAppInfoTranslations {
        SettingsAppInfoTranslations(manager: manager)
    }

    public var developer: SettingsDeveloperTranslations {
        SettingsDeveloperTranslations(manager: manager)
    }

    public var language: SettingsLanguageTranslations {
        SettingsLanguageTranslations(manager: manager)
    }

    public var preferences: SettingsPreferencesTranslations {
        SettingsPreferencesTranslations(manager: manager)
    }

    public var loadingLanguage: String {
        manager.translate("settings.loadingLanguage", default: "Loading language…")
    }

    public var logout: String {
        manager.translate("settings.logout", default: "Logout")
    }

    public var saving: String {
        manager.translate("settings.saving", default: "Saving…")
    }

    public var title: String {
        manager.translate("settings.title", default: "Settings")
    }
}

@MainActor
public struct SettingsAccountTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var changePassword: String {
        manager.translate("settings.account.changePassword", default: "Change Password")
    }

    public var profile: String {
        manager.translate("settings.account.profile", default: "Edit Profile")
    }

    public var title: String {
        manager.translate("settings.account.title", default: "Account")
    }

    public var twoFactorAuth: String {
        manager.translate("settings.account.twoFactorAuth", default: "Two-Factor Auth (2FA)")
    }

    public var twoFactorAuthOn: String {
        manager.translate("settings.account.twoFactorAuthOn", default: "On")
    }
}

@MainActor
public struct SettingsAppInfoTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var aboutApp: String {
        manager.translate("settings.appInfo.aboutApp", default: "About App")
    }

    public var contactSupport: String {
        manager.translate("settings.appInfo.contactSupport", default: "Contact Support")
    }

    public var title: String {
        manager.translate("settings.appInfo.title", default: "App Info")
    }
}

@MainActor
public struct SettingsDeveloperTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var debugMode: String {
        manager.translate("settings.developer.debugMode", default: "Debug Mode")
    }

    public var title: String {
        manager.translate("settings.developer.title", default: "Developer")
    }
}

@MainActor
public struct SettingsLanguageTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var updating: String {
        manager.translate("settings.language.updating", default: "Updating language...")
    }
}

@MainActor
public struct SettingsPreferencesTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var currency: String {
        manager.translate("settings.preferences.currency", default: "Currency / Units")
    }

    public var currencyUsd: String {
        manager.translate("settings.preferences.currencyUsd", default: "USD ($)")
    }

    public var darkMode: String {
        manager.translate("settings.preferences.darkMode", default: "Dark Mode")
    }

    public var language: String {
        manager.translate("settings.preferences.language", default: "Language")
    }

    public var notifications: String {
        manager.translate("settings.preferences.notifications", default: "Push Notifications")
    }

    public var title: String {
        manager.translate("settings.preferences.title", default: "Preferences")
    }
}

@MainActor
public struct ShellTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var tab: ShellTabTranslations {
        ShellTabTranslations(manager: manager)
    }
}

@MainActor
public struct ShellTabTranslations {
    private let manager: any LocalizationService

    public init(manager: any LocalizationService) {
        self.manager = manager
    }

    public var home: String {
        manager.translate("shell.tab.home", default: "Home")
    }

    public var scanner: String {
        manager.translate("shell.tab.scanner", default: "Scan")
    }

    public var settings: String {
        manager.translate("shell.tab.settings", default: "Settings")
    }
}
