// swift-tools-version: 6.0
import PackageDescription

/// `{{name.pascalCase()}}Feature` — generated by the `ios_mvi_feature` Mason brick
/// (Source Spec §10). Mirrors `SettingsFeature`, the template's worked example
/// (Source Spec §4.4 / §11).
///
/// See: Packages/Features/SettingsFeature/Package.swift
///
/// **Layer layout** (ArchTests K2 / K3 / K4 / K5):
///   * `Domain/**`       — pure Swift; no SwiftUI / UIKit / Combine.
///   * `Data/**`         — every declaration `internal`; reached only through
///                         the `Domain` protocol.
///   * `Presentation/**` — `{{name.pascalCase()}}Action` / `State` / `Event`,
///                         `{{name.pascalCase()}}ViewModel`, `View`,
///                         `RouteProvider`.
///   * `{{name.pascalCase()}}FeatureModule.swift` (top level) — the one seam that
///                         wires `Data` → `Domain` → `Presentation`.
let package = Package(
    name: "{{name.pascalCase()}}Feature",
    // `.iOS(.v16)` is the product floor. `.macOS(.v13)` is added ONLY so
    // `swift test --package-path Packages/Features/{{name.pascalCase()}}Feature`
    // runs on the macOS host. It imposes nothing on app consumers.
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "{{name.pascalCase()}}Feature", targets: ["{{name.pascalCase()}}Feature"]),
    ],
    dependencies: [
        .package(path: "../../AppUIKit"),
        .package(path: "../../Framework"),{{#has_network}}
        .package(path: "../../Network"),{{/has_network}}
        .package(path: "../../Platform"),
    ],
    targets: [
        .target(
            name: "{{name.pascalCase()}}Feature",
            dependencies: [
                .product(name: "AppUIKit", package: "AppUIKit"),
                .product(name: "Framework", package: "Framework"),{{#has_network}}
                .product(name: "Network", package: "Network"),{{/has_network}}
                .product(name: "Platform", package: "Platform"),
            ]
        ),
        .testTarget(
            name: "{{name.pascalCase()}}FeatureTests",
            dependencies: ["{{name.pascalCase()}}Feature"]
        ),
    ]
)
