import Combine
import XCTest
@testable import {{feature.pascalCase()}}

/// ### BDD Scenarios (Source Spec §9A Tier A — starter suite)
///
/// Generated by the `ios_mvi_subfeature` brick. Grow it to cover every §9A
/// Tier A category, mirroring `SettingsTests`.
/// See: Features/Settings/Tests/SettingsTests/SettingsViewModelTests.swift
@MainActor
final class {{name.pascalCase()}}ViewModelTests: XCTestCase {
    func testIncrementBumpsTheCounter() {
        let sut = {{name.pascalCase()}}ViewModel()

        sut.dispatch(.increment)

        XCTAssertEqual(sut.uiState.count, 1)
    }

    func testEveryFifthIncrementEmitsAMilestoneEvent() {
        let sut = {{name.pascalCase()}}ViewModel()
        var milestones: [Int] = []
        let token = sut.eventSubject.sink { event in
            if case let .milestone(value) = event {
                milestones.append(value)
            }
        }

        for _ in 0 ..< 10 {
            sut.dispatch(.increment)
        }
        token.cancel()

        XCTAssertEqual(milestones, [5, 10])
    }
}
