// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Flutter
import Foundation

public struct PluginDataMessage: Sendable {
    public var id: String
    public var title: String

    public init(id: String, title: String) {
        self.id = id
        self.title = title
    }

    static func fromList(_ list: [Any?]) -> PluginDataMessage? {
        guard let id = list[0] as? String,
              let title = list[1] as? String
        else {
            return nil
        }
        return PluginDataMessage(id: id, title: title)
    }

    func toList() -> [Any?] {
        [id, title]
    }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 128:
            guard let list = readValue() as? [Any?] else { return nil }
            return PluginDataMessage.fromList(list)
        default:
            return super.readValue(ofType: type)
        }
    }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let value = value as? PluginDataMessage {
            super.writeByte(128)
            super.writeValue(value.toList())
        } else {
            super.writeValue(value)
        }
    }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader {
        MessagesPigeonCodecReader(data: data)
    }

    override func writer(with data: NSMutableData) -> FlutterStandardWriter {
        MessagesPigeonCodecWriter(data: data)
    }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
    static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

public protocol MyPluginHostApi {
    func getData(completion: @escaping @Sendable (Result<PluginDataMessage, Error>) -> Void)
}

public enum MyPluginHostApiSetup {
    public static var codec: FlutterStandardMessageCodec {
        MessagesPigeonCodec.shared
    }

    public static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MyPluginHostApi?) {
        let channel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.MyPluginHostApi.getData",
            binaryMessenger: binaryMessenger,
            codec: codec
        )
        if let api {
            channel.setMessageHandler { _, reply in
                api.getData { result in
                    switch result {
                    case let .success(res):
                        reply(wrapResult(res))
                    case let .failure(error):
                        reply(wrapError(error))
                    }
                }
            }
        } else {
            channel.setMessageHandler(nil)
        }
    }
}

private func wrapResult(_ result: Any?) -> [Any?] {
    [result]
}

private func wrapError(_ error: Any) -> [Any?] {
    if let flutterError = error as? FlutterError {
        return [
            flutterError.code,
            flutterError.message,
            flutterError.details,
        ]
    }
    return [
        "\(error)",
        "\(error)",
        nil,
    ]
}
