#!/usr/bin/env bash
#
# rename_project.sh — the single entry point after cloning this template.
# ---------------------------------------------------------------------------
# Renames the shipped project identity `iOSDigitalWallet` /
# `com.danhdue.iOSDigitalWallet` to your own app name + bundle id.
#
# Usage:
#   ./scripts/rename_project.sh <NewAppName> <new.bundle.id>
#   ./scripts/rename_project.sh AcmeApp com.acme.app
#
#   <NewAppName>    a valid Swift identifier: ^[A-Za-z][A-Za-z0-9]*$
#                   (no spaces, no punctuation — it becomes the Tuist project
#                   name, the scheme name and the `@main` struct name)
#   <new.bundle.id> reverse-DNS bundle id: ^[a-z0-9]+(\.[a-z0-9]+)+$
#
# What it rewrites (Source Spec §12):
#   * Tuist manifests            — Project.swift, Workspace.swift,
#                                  Tuist/Package.swift
#   * App identity               — App/Sources/**, App/Tests/**,
#                                  App/Resources/Info.plist
#   * Docs / CI                  — *.md at repo root, docs/**/*.md,
#                                  .github/workflows/*.yml
#   * The bundle id              — Project.swift, App/Resources/Info.plist,
#                                  App/Sources/Composition/ConsoleLogger.swift,
#                                  App/Tests/**
#   * Renames App/Sources/iOSDigitalWalletApp.swift -> <NewAppName>App.swift
#     via `git mv` (history preserved).
#
# What it NEVER touches (fixed "vendor namespace"):
#   Packages/**  bricks/**  ArchTests/**  scripts/**  .devtool/**
#   — the infra / Shell / *Feature package names (Core, Framework, Network,
#     AppUIKit, Platform, Shell, SettingsFeature, ScannerFeature) stay put so
#     Mason brick output is stable across every renamed project.
#
# `.xcodeproj` / `.xcworkspace` are generated by Tuist and git-ignored — there
# is no `.pbxproj` surgery here.
#
# Environment:
#   RENAME_SKIP_VERIFY=1   skip the `tuist generate` + `xcodebuild build`
#                          verification step (useful for a dry run).
#
# Exit status: 0 on success (or when the project is already renamed), 1 on any
# validation failure, non-zero if the verification build fails.

set -eu

OLD_NAME="iOSDigitalWallet"
OLD_BUNDLE="com.danhdue.iOSDigitalWallet"
APP_ENTRY="App/Sources/${OLD_NAME}App.swift"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

usage() {
  cat >&2 <<EOF
usage: ./scripts/rename_project.sh <NewAppName> <new.bundle.id>

  <NewAppName>     valid Swift identifier  ^[A-Za-z][A-Za-z0-9]*\$   e.g. AcmeApp
  <new.bundle.id>  reverse-DNS bundle id   ^[a-z0-9]+(\.[a-z0-9]+)+\$  e.g. com.acme.app

example:
  ./scripts/rename_project.sh AcmeApp com.acme.app
EOF
}

die() {
  echo "rename_project: $1" >&2
  exit 1
}

# --- portable in-place sed (BSD vs GNU), detected once --------------------
if sed --version >/dev/null 2>&1; then
  _sed_inplace() { LC_ALL=C sed -i -e "$1" "$2"; }   # GNU
else
  _sed_inplace() { LC_ALL=C sed -i '' -e "$1" "$2"; } # BSD / macOS
fi

# replace <pattern> <replacement> <file...> — skips files that do not exist,
# only rewrites files that actually contain the pattern.
replace_in() {
  pattern="$1"; replacement="$2"; shift 2
  for f in "$@"; do
    [ -f "$f" ] || continue
    if LC_ALL=C grep -q -e "$pattern" "$f"; then
      _sed_inplace "s/${pattern}/${replacement}/g" "$f"
      echo "  rewrote  $f"
      TOUCHED=$((TOUCHED + 1))
    fi
  done
}

# ------------------------------------------------------------------------
# 1. Validate arguments (independent of tree state)
# ------------------------------------------------------------------------
if [ "$#" -ne 2 ]; then
  usage
  exit 1
fi

NEW_NAME="$1"
NEW_BUNDLE="$2"

printf '%s' "$NEW_NAME" | LC_ALL=C grep -Eq '^[A-Za-z][A-Za-z0-9]*$' \
  || die "invalid app name '$NEW_NAME' — must match ^[A-Za-z][A-Za-z0-9]*\$ (a valid Swift identifier, no spaces)"

printf '%s' "$NEW_BUNDLE" | LC_ALL=C grep -Eq '^[a-z0-9]+(\.[a-z0-9]+)+$' \
  || die "invalid bundle id '$NEW_BUNDLE' — must match ^[a-z0-9]+(\.[a-z0-9]+)+\$ (reverse-DNS, lowercase)"

# ------------------------------------------------------------------------
# 2. Idempotency guard — bail cleanly if already renamed
# ------------------------------------------------------------------------
if [ ! -f "$APP_ENTRY" ] && ! LC_ALL=C grep -q "$OLD_NAME" Project.swift 2>/dev/null; then
  echo "rename_project: nothing to do — project already renamed"
  echo "  ('$OLD_NAME' token absent from Project.swift and $APP_ENTRY already moved)."
  exit 0
fi

# ------------------------------------------------------------------------
# 3. Require a clean git tree
# ------------------------------------------------------------------------
if [ -n "$(git status --porcelain)" ]; then
  die "working tree is dirty — commit or stash your changes first"
fi

# ------------------------------------------------------------------------
# 4. Collect the file lists
# ------------------------------------------------------------------------
swift_sources=""
[ -d App/Sources ] && swift_sources="$(find App/Sources -type f -name '*.swift')"
swift_tests=""
[ -d App/Tests ] && swift_tests="$(find App/Tests -type f -name '*.swift')"
root_md="$(find . -maxdepth 1 -type f -name '*.md')"
docs_md=""
[ -d docs ] && docs_md="$(find docs -type f -name '*.md')"
ci_yml=""
[ -d .github/workflows ] && ci_yml="$(find .github/workflows -type f \( -name '*.yml' -o -name '*.yaml' \))"

# shellcheck disable=SC2086
name_files="Project.swift Workspace.swift Tuist/Package.swift App/Resources/Info.plist quality/.swiftlint.yml quality/.swiftformat $swift_sources $swift_tests $root_md $docs_md $ci_yml"
# shellcheck disable=SC2086
bundle_files="Project.swift App/Resources/Info.plist App/Sources/Composition/ConsoleLogger.swift $swift_tests"

TOUCHED=0

echo "rename_project: $OLD_NAME -> $NEW_NAME   |   $OLD_BUNDLE -> $NEW_BUNDLE"
echo

# ------------------------------------------------------------------------
# 5. Bundle id FIRST (its string contains the name token as a prefix),
#    then the project name.
# ------------------------------------------------------------------------
echo "bundle id:"
# shellcheck disable=SC2086
replace_in 'com\.danhdue\.iOSDigitalWallet' "$NEW_BUNDLE" $bundle_files

echo "project name:"
# shellcheck disable=SC2086
replace_in 'iOSDigitalWallet' "$NEW_NAME" $name_files

# ------------------------------------------------------------------------
# 6. Move the @main entry-point file (struct body already rewritten above)
# ------------------------------------------------------------------------
MOVED="(none — $APP_ENTRY not found)"
if [ -f "$APP_ENTRY" ]; then
  git mv "$APP_ENTRY" "App/Sources/${NEW_NAME}App.swift"
  MOVED="git mv $APP_ENTRY -> App/Sources/${NEW_NAME}App.swift"
  echo "  $MOVED"
fi

# ------------------------------------------------------------------------
# 7. Verify: regenerate the project and build the renamed scheme
# ------------------------------------------------------------------------
VERIFY="SKIPPED (RENAME_SKIP_VERIFY=1)"
if [ "${RENAME_SKIP_VERIFY:-0}" != "1" ]; then
  echo
  echo "verify: tuist install"
  tuist install
  echo "verify: tuist generate --no-open"
  tuist generate --no-open
  echo "verify: xcodebuild build -scheme $NEW_NAME"
  if xcodebuild build \
      -workspace "${NEW_NAME}.xcworkspace" \
      -scheme "$NEW_NAME" \
      -destination 'generic/platform=iOS Simulator' \
      CODE_SIGNING_ALLOWED=NO; then
    VERIFY="PASS"
  else
    VERIFY="FAIL"
  fi
fi

# ------------------------------------------------------------------------
# 8. Summary
# ------------------------------------------------------------------------
echo
echo "=================== rename_project summary ==================="
echo "  app name    : $OLD_NAME  ->  $NEW_NAME"
echo "  bundle id   : $OLD_BUNDLE  ->  $NEW_BUNDLE"
echo "  files rewritten : $TOUCHED"
echo "  entry point : $MOVED"
echo "  verify      : $VERIFY"
echo "  next        : review 'git diff', then commit; run 'mason get' for the bricks."
echo "============================================================="

[ "$VERIFY" = "FAIL" ] && exit 1
exit 0
