// swift-tools-version: 6.0
import PackageDescription

/// `{{name.pascalCase()}}Feature` — generated by the `ios_mvi_feature` Mason brick
/// (Source Spec §10). Mirrors `Settings`, the template's worked example
/// (Source Spec §4.4 / §11).
///
/// See: Features/Settings/Package.swift
///
/// **Layer layout** (ArchTests K2 / K3 / K4 / K5):
///   * `Domain/**`       — pure Swift; no SwiftUI / UIKit / Combine.
///   * `Data/**`         — every declaration `internal`; reached only through
///                         the `Domain` protocol.
///   * `Presentation/**` — `{{name.pascalCase()}}Action` / `State` / `Event`,
///                         `{{name.pascalCase()}}ViewModel`, `View`,
///                         `RouteProvider`.
///   * `{{name.pascalCase()}}Container.swift` (top level) — Factory `Container` extensions
///                         that register `Data` → `Domain` dependencies.
let package = Package(
    name: "{{name.pascalCase()}}",
    // `.iOS(.v16)` is the product floor. `.macOS(.v13)` is added ONLY so
    // `swift test --package-path Features/{{name.pascalCase()}}`
    // runs on the macOS host. It imposes nothing on app consumers.
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "{{name.pascalCase()}}", targets: ["{{name.pascalCase()}}"]),
    ],
    dependencies: [
        .package(path: "../../Packages/AppUIKit"),
        .package(path: "../../Packages/Framework"),{{#has_network}}
        .package(path: "../../Packages/Network"),{{/has_network}}
        .package(path: "../../Packages/Platform"),
    ],
    targets: [
        .target(
            name: "{{name.pascalCase()}}",
            dependencies: [
                .product(name: "AppUIKit", package: "AppUIKit"),
                .product(name: "Framework", package: "Framework"),{{#has_network}}
                .product(name: "Network", package: "Network"),{{/has_network}}
                .product(name: "Platform", package: "Platform"),
            ]
        ),
        .testTarget(
            name: "{{name.pascalCase()}}Tests",
            dependencies: ["{{name.pascalCase()}}"]
        ),
    ]
)
