import Core
import Platform
import SwiftUI
import XCTest
@testable import {{name.pascalCase()}}Feature

/// ### BDD Scenarios (Source Spec §9A Tier A — fill these in before shipping)
///
/// This is a **starter** suite generated by the `ios_mvi_feature` brick. Grow it
/// to cover every §9A Tier A category, mirroring
/// `SettingsFeatureTests` (the worked example):
///
/// 1. **Happy path** — `.onAppear` loads the persisted value → `viewState`
///    becomes `content`; each mutating action persists the new value.
///    See: Packages/Features/SettingsFeature/Tests/SettingsFeatureTests/SettingsViewModelTests.swift
/// 2. **Boundary / partition** — empty title rejected; `.default` when the store
///    is empty; a corrupt cache degrades to `.default` + a logged `.error`
///    (drive a real `{{name.pascalCase()}}RepositoryImpl` over an in-memory
///    `CacheStore`, like `SettingsViewModelTests`).
/// 3. **State transition** — every valid `Action → State` edge, plus the ignored
///    `.titleChanged("")` edge.
/// 4. **Async / race** — dispatch a mutating action ≥3× fast: only the last
///    reaches `save`; `onClear()` cancels in-flight effects; no emission after
///    `onClear()`. See:
///    Packages/Features/SettingsFeature/Tests/SettingsFeatureTests/SaveCoalescingTests.swift
/// 5. **Failure injection** — `saveResult = .error(...)` → optimistic change
///    reverts and `.saveFailed` is emitted. See:
///    Packages/Features/SettingsFeature/Tests/SettingsFeatureTests/FailureInjectionTests.swift
/// 6. **Emission order** — assert the `viewState` *sequence*
///    (`loading → content`, `loading → error`), not just the final value. See:
///    Packages/Features/SettingsFeature/Tests/SettingsFeatureTests/EmissionOrderTests.swift
/// 7. **Resource teardown** — `effectTasks` empty after `onClear()`. See:
///    Packages/Features/SettingsFeature/Tests/SettingsFeatureTests/TeardownTests.swift
@MainActor
final class {{name.pascalCase()}}ViewModelTests: XCTestCase {
    // MARK: onAppear (happy path — scenario 1)

    func testOnAppearLoadsStoredValueAndShowsContent() async {
        let repo = Spy{{name.pascalCase()}}Repository()
        let stored = {{name.pascalCase()}}Entity(title: "loaded", count: 7)
        repo.loadResult = .success(stored)
        let sut = {{name.pascalCase()}}ViewModel(repository: repo)

        sut.dispatch(.onAppear)
        await poll { sut.viewState.tag == "content" }

        XCTAssertEqual(sut.viewState.tag, "content")
        XCTAssertEqual(sut.uiState.entity, stored)
        XCTAssertEqual(repo.loadCallCount, 1)
    }

    // MARK: mutating action persists (scenario 3)

    func testIncrementOptimisticallyBumpsCountAndPersists() async {
        let repo = Spy{{name.pascalCase()}}Repository()
        let sut = {{name.pascalCase()}}ViewModel(repository: repo)
        sut.dispatch(.onAppear)
        await poll { sut.viewState.tag == "content" }

        sut.dispatch(.increment)
        XCTAssertEqual(sut.uiState.entity.count, 1, "optimistic reduce is synchronous")

        await poll { sut.uiState.isSaving == false }
        XCTAssertEqual(repo.savedEntities.last?.count, 1)
    }

    // MARK: RouteProvider (scenario: canHandle)

    func testRouteProviderHandlesOwnRouteOnly() {
        let provider = {{name.pascalCase()}}RouteProvider {
            {{name.pascalCase()}}ViewModel(repository: Spy{{name.pascalCase()}}Repository())
        }

        XCTAssertTrue(provider.canHandle({{name.pascalCase()}}Root()))
        XCTAssertFalse(provider.canHandle(AppRoutes.SettingsRoot()))
    }
}
